# Generated by Django 4.0.5 on 2022-07-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_hospital_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('blood_grp', models.CharField(choices=[('DEA-1.1', 'DEA-1.1'), ('DEA-1.2', 'DEA-1.2'), ('DEA-3', 'DEA-1.2'), ('DEA-4', 'DEA-1.2'), ('DEA-5', 'DEA-5'), ('DEA-7', 'DEA-7')], max_length=100)),
            ],
        ),
    ]
