# Generated by Django 4.0.5 on 2023-06-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_donors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='blood_grp',
            field=models.CharField(choices=[('', 'Blood Group'), ('DEA-1.1', 'DEA-1.1'), ('DEA-1.2', 'DEA-1.2'), ('DEA-3', 'DEA-1.2'), ('DEA-4', 'DEA-1.2'), ('DEA-5', 'DEA-5'), ('DEA-7', 'DEA-7')], max_length=100),
        ),
    ]
